# -*- coding: utf-8 -*-
"""live_translate

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ztWU1KHzdJqfLMxvLckPWx46G2lkQsgs
"""

# live_translate.py

import whisper
from googletrans import Translator
from transformers import pipeline
import sounddevice as sd
import numpy as np
import tempfile
import wave
import pandas as pd
from datetime import datetime

# ----------------------------
# 1. Initialize Models
# ----------------------------
print("Loading Whisper model...")
whisper_model = whisper.load_model("small")  # choose small/medium for balance of speed and accuracy
translator = Translator()

# Optional summarization model
summarizer = pipeline("summarization", model="facebook/bart-large-cnn")

# ----------------------------
# 2. Configuration
# ----------------------------
TARGET_LANGUAGE = input("Enter target language (e.g., 'en', 'fr', 'de'): ")
RECORD_DURATION = int(input("Enter per-recording duration in seconds (e.g., 10): "))

# Data storage
meeting_transcripts = []

# ----------------------------
# 3. Audio Recording Function
# ----------------------------
def record_audio(duration=10, fs=16000):
    print(f"\nRecording for {duration} seconds...")
    recording = sd.rec(int(duration * fs), samplerate=fs, channels=1)
    sd.wait()
    recording = (recording * 32767).astype(np.int16)

    tmp_file = tempfile.NamedTemporaryFile(delete=False, suffix=".wav")
    with wave.open(tmp_file.name, 'wb') as wf:
        wf.setnchannels(1)
        wf.setsampwidth(2)
        wf.setframerate(fs)
        wf.writeframes(recording.tobytes())
    return tmp_file.name

# ----------------------------
# 4. Transcribe Function
# ----------------------------
def transcribe_audio(audio_file):
    result = whisper_model.transcribe(audio_file)
    transcript = result['text']
    return transcript

# ----------------------------
# 5. Translate Function
# ----------------------------
def translate_text(text, target_language):
    translation = translator.translate(text, dest=target_language)
    return translation.text

# ----------------------------
# 6. Summarization Function
# ----------------------------
def summarize_text(text):
    # Limit length for summarization
    max_length = min(len(text.split()), 500)
    if max_length < 50:  # too short to summarize
        return text
    summary = summarizer(text, max_length=100, min_length=30, do_sample=False)
    return summary[0]['summary_text']

# ----------------------------
# 7. Main Loop - Continuous Recording
# ----------------------------
print("\nStarting LiveTranslate. Press Ctrl+C to stop.")

try:
    while True:
        audio_file = record_audio(RECORD_DURATION)

        # Transcription
        transcript = transcribe_audio(audio_file)
        print(f"\nTranscript:\n{transcript}")

        # Translation
        translation = translate_text(transcript, TARGET_LANGUAGE)
        print(f"\nTranslation ({TARGET_LANGUAGE}):\n{translation}")

        # Summarization
        summary = summarize_text(transcript)
        print(f"\nSummary:\n{summary}")

        # Timestamp
        timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

        # Save to memory
        meeting_transcripts.append({
            "Timestamp": timestamp,
            "Transcript": transcript,
            "Translation": translation,
            "Summary": summary
        })

except KeyboardInterrupt:
    print("\nStopping LiveTranslate...")

# ----------------------------
# 8. Export Meeting Notes
# ----------------------------
output_file = f"meeting_notes_{datetime.now().strftime('%Y%m%d_%H%M%S')}.csv"
df = pd.DataFrame(meeting_transcripts)
df.to_csv(output_file, index=False)
print(f"\nMeeting notes saved to {output_file}")